style:
  MaxLineLength:
    active: false
  MagicNumber:
    ignoreAnnotated: [ 'TestDataFactory' ]
  UnusedPrivateMember:
    ignoreAnnotated: [ 'Preview', 'WearPreviewDevices', 'WearPreviewFontScales' ]

naming:
  FunctionNaming:
    ignoreAnnotated: [ 'Composable' ]
    excludes: "**/test/**,**/androidTest/**,**/androidUnitTest/**"
